version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - "./src:/home/node/app/src"
      - "./tsconfig.json:/home/node/app/tsconfig.json"
      - "./webpack.config.js:/home/node/app/webpack.config.js"
    links:
      - db
    command: "npm run dev"
    restart: unless-stopped
    environment:
      - TYPEORM_HOST=db
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=root-password
      - TYPEORM_DATABASE=shooting-stars
      - TYPEORM_PORT=3306
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=true
  python:
    build: python
    scale: 0
    volumes:
      - "./python/src:/home/python/app/src"
      - "./python/out:/home/python/app/out"
    links:
      - db
    command: "python3 src/generate_stars.py"
    environment:
      - TYPEORM_HOST=db
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=root-password
      - TYPEORM_DATABASE=shooting-stars
      - TYPEORM_PORT=3306
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shooting-stars
      MYSQL_ROOT_PASSWORD: root-password
    volumes:
      - mysql-datavolume:/var/lib/mysql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  mysql-datavolume:
