export enum WorldMode {
  STANDARD = "STANDARD",
  BETA = "BETA",
  DEADMAN = "DEADMAN",
  PVP_ARENA = "PVP_ARENA",
  SHATTERED_RELICS_LEAGUE = "SHATTERED_RELICS_LEAGUE",
  QUEST_SPEEDRUNNING = "QUEST_SPEEDRUNNING",
}
